Workaround for missing `str.isascii()` in Python 3.6